# Generated by Django 3.2.5 on 2021-10-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoistureContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tare_id', models.CharField(max_length=20, unique=True)),
                ('tare_mass', models.DecimalField(decimal_places=1, max_digits=10)),
                ('tare_and_material_wet_mass', models.DecimalField(decimal_places=1, max_digits=10)),
                ('dry_mass_bal', models.CharField(choices=[('01BAL', '01BAL'), ('02BAL', '02BAL')], default='01BAL', max_length=10)),
                ('tare_and_material_dry_mass', models.DecimalField(decimal_places=1, max_digits=10)),
                ('report', models.CharField(blank=True, choices=[('ISM', 'Insufficient Sample Mass'), ('DT', 'Drying Temperature'), ('ME', 'Material Excluded')], max_length=200, null=True)),
            ],
        ),
    ]
